---

language: ruby
cache: bundler

install:
  - bundle install

before_script:
  - echo "-----BEGIN RSA PRIVATE KEY-----" > ./ssh_key
  - echo "$PRIVATE_SSH_KEY" >> ./ssh_key
  - echo "-----END RSA PRIVATE KEY-----" >> ./ssh_key
  - cat ./ssh_key
  - chmod 600 ./ssh_key
  - eval "$(ssh-agent -s)"
  - ssh-add ./ssh_key

script:
  - kitchen test
